### PR TITLE
Introduce several changes on geoclimate

### PR DESCRIPTION
**Pull request by ebocher**
- do not use highway= pedestrian and area=yes in the RSU process. This area must be considered in impervious layer.
- merge all tables one by one when the area is defined with a multipolygon, to obtain a continous domain
- use postfix instead of prefix to set a unique name for the output results. Indeed sometimes prefix is empty
- upgrade xstream lib

### CODE REVIEW

**Comment by j3r3m1** [comment]
>     * use postfix instead of prefix to set a unique name for the output results. Indeed sometimes prefix is empty
Is this really useful ? The prefix is used to distinguish two calculations. Using postfix makes it difficult to debug sometimes since it is difficult to know which is the last one. Moreover, it could lead to enormous databases if the database is not deleted regularly.

**Comment by ebocher** [comment]
I' d like to said. Absolutely yes ,-)
Imagine you are running a workflow on two locations. Currently and for a few tables, the name of the ouput table is the same, this is the case for INPUT_ROAD. So you can't keep in the H2GIS database, the input_road table for both locations. Only the last one will be stored. This PR fixes this issue for all all output tables computed by the workflows.

**Comment by ebocher** [comment]
Yes this will require some code and tests. 
but this does not solve the problem of tables with the same names. Or the user has to put a prefix by himself, which is very heavy.

**Comment by ebocher** [comment]
Note that you can easly get the name of tables when a workflow is finished
e.g  process.getResults().output["Pont-de-Veyle"]["roadTrafficTableName"]

**Comment by j3r3m1** [comment]
Bonjour,
    Je suis actuellement absent du bureau jusqu'au 15 octobre.
    Cordialement,
    Jérémy
    --
    Hi,
    I am actually out of office up to October the 15th.
    Best regards,
    Jérémy

**Pull request merged**
