### PR TITLE
copernicus doc. configuration

### PR DESCRIPTION
**Pull request by ernlt**
This PR aims at describing the Geoclimate deployment and execution process, for one or several domains, on HPC server at ECMWF.

### CODE REVIEW

**Comment by ebocher** [comment]
Thanks for the doc, but this doc must be on the Corpenicus website as page.
@ELSW56

**Comment by ELSW56** [comment]
@ernlt, could you please integrate your doc at the place we defined together last friday :
https://confluence.ecmwf.int/display/SLIM/Documentation+and+user+manuel
Even though parts of the doc could find their place here, the special developments for SLIM, linked with the use of the HPC server, have nothing to see with the generic geoclimate project.

**Comment by ernlt** [comment]
@ebocher @ELSW56 
I should have ask you before creating this PR, as I wanted to make a link between the webpage of Copernicus and this location. 
I thought it would have be easier to read the documentation at .pdf file format. So, I will integrate this documentation directly on the page mentioned last time.

**Comment by ebocher** [comment]
I close this PR because the doc is under integration in Copernicus

**Pull request closed without merging**
