### PR TITLE
Geoindicators and fixes

### PR DESCRIPTION
**Pull request by ebocher**
This PR adds the block chain to compute indicators.
It introduces several fixes as validation for each processes on chains.
It offers also a new data util to save the tables as files.
The OSM extract process has been fixed to avoid null type on road and building.

### CODE REVIEW

**Comment by ebocher** [comment]
humm don't understand why it doesn't compile here. Perhaps a time out on travis...
@SPalominos

**Comment by SPalominos** [comment]
@ebocher It's caused by the 'executeScript' instruction which should use a Stream instead of a file path.

**Comment by ebocher** [comment]
@SPalominos 
Dring

**Comment by ebocher** [comment]
@SPalominos 
Feel free to merge this giant PR

**Comment by ebocher** [comment]
Thanks let's start the last indicators

**Pull request merged**
