### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by franetibe**
A first set of screenshots for the tutorial.

### CODE REVIEW

**Comment by ebocher** [comment]
Thanks. It'd be nice to add generic file paths in the figure, e.g. /tmp/myconfig.json instead of the user one.

**Comment by franetibe** [comment]
You mean in the screenshots for the groovy console ?

Do you want to locate the config file in the \tmp folder ?

**Comment by ebocher** [comment]
> You mean in the screenshots for the groovy console ?

Yes . You can use /home/mydirectory/myconfigfile.json

**Comment by franetibe** [comment]
Ok. Should I close this PR and open a new one with new screenshots ?

**Comment by j3r3m1** [comment]
Did you make the change from github or from your local Geoclimate repo ? If from GitHub maybe it is easier to reopen a new PR yes. Otherwise you just have to update the files on your local branch and then commit and push to your remote repo.

**Comment by franetibe** [comment]
I just use github.com, no local branch so far
I will close this issue and open a new one 
Thanks !

**Pull request closed without merging**
