### PR TITLE
Update utrf name

### PR DESCRIPTION
**Pull request by j3r3m1**
Modifications according to #557 
Remains doc to update

### CODE REVIEW

**Comment by ebocher** [comment]
In BDTopo and OSM workflows the saved tables must be updated also https://github.com/orbisgis/geoclimate/blob/6a00173c420f06157df4622041a9f504e214859d/osm/src/main/groovy/org/orbisgis/geoclimate/osm/WorkflowOSM.groovy#L824
What about rsu_urtf_area ?

**Comment by j3r3m1** [comment]
> In BDTopo and OSM workflows the saved tables must be updated also
> 
> https://github.com/orbisgis/geoclimate/blob/6a00173c420f06157df4622041a9f504e214859d/osm/src/main/groovy/org/orbisgis/geoclimate/osm/WorkflowOSM.groovy#L824
> 
> What about rsu_urtf_area ?

There are a lot of variables or names using "urban_typo" and I though only solving the ones at "top" scale would be sufficient

**Comment by ebocher** [comment]
ok

**Comment by ebocher** [comment]
Fixed

**Pull request closed without merging**
