### PR TITLE
Make input geometries valid when necessary

### LINKED ISSUE #244: Workflow BDTopo - 56184
I still have trouble with this commune when calculating the water fraction:
Only dimension >=2 should be kept before intersection.

### PR DESCRIPTION
**Pull request by gpetit**
When necessary, make input geometries valid.

-> When geom is not valid then ST_MakeValid

This PR is supposed to resolve #244 #245 #247

### CODE REVIEW

**Comment by j3r3m1** [comment]
Which solution did you finally choose for the statistics ?
Is it possible to add a test to verify that problems are solved (for example testing the intersection of the rsu previously identified in #244 and the water fraction that will be imported with this update script ?

**Comment by gpetit** [comment]
No options were chosen.
I left it as it is. So in theory we will have to count 0 invalid objects.

In time, I will see to extract the quality tests and make them optional. It is a big job that will be done once everything is working and we start producing results.

Concerning the unit tests, why not. I have to have a look to see where they have to be ...

**Comment by j3r3m1** [comment]
I would say in the following file in a new test
https://github.com/orbisgis/geoclimate/blob/master/preparedata/src/test/groovy/org/orbisgis/orbisprocess/geoclimate/preparedata/bdtopo/BDTopoGISLayersTest.groovy

**Comment by gpetit** [comment]
Ah ok. So I will add on the fly the RSU geom to test the interesection with an existing input (water or veget) geom.
Since my unit tests are made on Vannes, I have to see if we have problematic geom

**Comment by gpetit** [comment]
Ok I found a water geom that creates an error with a RSU in Vannes

HYDRO
- ID_HYDRO : `99`
- ID_SOURCE : `SURF_EAU0000000087197136`
- THE_GEOM : `POLYGON ((265839.4 6746589.6, 265841 6746596.1, 265841.1 6746597.6, 265841.8 6746599.1, 265843.2 6746600, 265844.4 6746600.6, 265846.1 6746600.9, 265848.7 6746600.2, 265849.9 6746599.6, 265850.9 6746599, 265851.3 6746597.8, 265851.7 6746596.4, 265852.6 6746592.9, 265853.1 6746590.9, 265852.9 6746588.6, 265851.9 6746586.4, 265849.5 6746584.9, 265848.2 6746584.5, 265846 6746584.3, 265844.5 6746584.4, 265843.2 6746584.6, 265841.6 6746585.1, 265840.3 6746586.6, 265839.4 6746589.6), (265821.3 6746585.2, 265822 6746580, 265823.3 6746570.8, 265823.7 6746569.3, 265824.1 6746568.3, 265825.1 6746566.7, 265826.6 6746565.8, 265828.6 6746565.6, 265831.5 6746566.4, 265833.2 6746567.2, 265836.4 6746569, 265843.7 6746572.6, 265859.2 6746581.3, 265861.9 6746583.1, 265862.9 6746584.1, 265864 6746585.8, 265865 6746588.1, 265863.1 6746602.4, 265861.6 6746612.2, 265859.5 6746615.3, 265857.3 6746616.6, 265854.3 6746616.7, 265852.5 6746616.3, 265847.2 6746613.4, 265839.8 6746609.5, 265831.2 6746604.4, 265825 6746599.6, 265823 6746596.4, 265821.9 6746593.7, 265821.3 6746590.7, 265821.3 6746585.2))`

RSU
- ID_RSU : `670`
- THE_GEOM : `POLYGON ((265652.709 6746320.319, 265652.5 6746320.3, 265650.2 6746320, 265649.6 6746320, 265648.7 6746323, 265645.2 6746322.6, 265642.2 6746322.1, 265637.7 6746323.1, 265636.6 6746320.1, 265633.1 6746320.7, 265618.2 6746323.1, 265617.5 6746331.4, 265624.8 6746333.2, 265625.7 6746328.2, 265629.2 6746326.7, 265634.2 6746325.6, 265639.2 6746326.6, 265647.2 6746328.5, 265651.2 6746330.5, 265652.7 6746333, 265651.8 6746337, 265662.3 6746341.4, 265667.3 6746344.4, 265672.3 6746345.3, 265678.3 6746343.3, 265683.3 6746340.2, 265684.2 6746337.2, 265679.2 6746334.3, 265683.2 6746333.2, 265687.2 6746334.2, 265692.2 6746337.2, 265688.3 6746343.2, 265687.3 6746346.2, 265688.3 6746349.2, 265691.4 6746352.2, 265694.9 6746353.6, 265696.4 6746359.1, 265698.4 6746363.1, 265701.5 6746366.1, 265708 6746368.5, 265711.5 6746376, 265716.6 6746384.9, 265724.7 6746392.9, 265725.2 6746400.3, 265721.2 6746402.4, 265718.3 6746407.4, 265720.8 6746410.9, 265722.3 6746414.4, 265726.4 6746416.3, 265728.9 6746422.8, 265732 6746431.8, 265736 6746439.7, 265739.6 6746445.2, 265738.1 6746450.7, 265739.2 6746454.7, 265744.2 6746457.7, 265749.5 6746459.4, 265750.6 6746449.1, 265755.6 6746449.1, 265757.5 6746455.5, 265756.2 6746459.6, 265757.7 6746463, 265767.2 6746465.8, 265775.7 6746464.9, 265777.7 6746468.9, 265783.3 6746472.3, 265787.8 6746474.8, 265789.8 6746478.8, 265794.3 6746481.2, 265797.8 6746482.7, 265799.9 6746486.7, 265804.4 6746489.1, 265805.9 6746491.6, 265805 6746497.6, 265811 6746499.6, 265816.4 6746497, 265820.5 6746503, 265823 6746507.5, 265826 6746508.5, 265827.6 6746519.9, 265830.6 6746522.9, 265835.7 6746529.9, 265837.2 6746533.3, 265842.7 6746534.8, 265840.3 6746539, 265837.8 6746541.8, 265835.8 6746545.8, 265832.9 6746548.9, 265828.9 6746549.9, 265824.9 6746548.9, 265817.8 6746546, 265813.9 6746548, 265807.9 6746550.1, 265802.4 6746548.6, 265800.718 6746549.787, 265803 6746551.4, 265805.9 6746554.6, 265807.6 6746558.7, 265808.9 6746565.1, 265809.5 6746577, 265809.6 6746578.504, 265809.6 6746578.5, 265821.1 6746574.9, 265824.1 6746573.9, 265827.1 6746573.9, 265827.1 6746576.9, 265826.1 6746579.9, 265825.6 6746582.9, 265829.2 6746596.9, 265831.8 6746603.3, 265841.3 6746600.8, 265848.8 6746600.2, 265851.9 6746607.4, 265856 6746609.2, 265853.6 6746612.4, 265848.3 6746613.2, 265842.9 6746618.3, 265842.9 6746621.155, 265851.4 6746625.2, 265863.4 6746630.1, 265873.3 6746573.8, 265879.4 6746555.9, 265888.159 6746538.63, 265888.1 6746538.7, 265886.7 6746540.4, 265883.3 6746542, 265882.3 6746545, 265876.8 6746544.5, 265873.3 6746543, 265873.5 6746538.6, 265877.2 6746528, 265880.1 6746527, 265878.6 6746520.5, 265875.6 6746521.5, 265872.6 6746518.6, 265868.6 6746518.2, 265861.1 6746517.2, 265858.5 6746512.7, 265854.5 6746506.7, 265849.4 6746497.8, 265839.4 6746487.9, 265837.3 6746481.9, 265834.8 6746477.4, 265830.3 6746474.9, 265822.7 6746468.5, 265819.2 6746470, 265816.2 6746469.1, 265811.2 6746466.1, 265809.2 6746472.1, 265804.3 6746475.2, 265801.7 6746470.7, 265796.2 6746469.2, 265784.7 6746465.8, 265784.7 6746462.8, 265787.7 6746461.8, 265787.6 6746454.8, 265784.6 6746453.8, 265783.5 6746442.8, 265780 6746441.4, 265783.5 6746439.8, 265782 6746435.4, 265777.9 6746429.4, 265774.9 6746430.4, 265765.9 6746421.5, 265762.4 6746420, 265761.3 6746417, 265753.8 6746415.6, 265749.8 6746411.6, 265746.3 6746410.2, 265745.2 6746397.2, 265741.7 6746395.7, 265737.2 6746393.3, 265735.1 6746389.3, 265731.6 6746387.8, 265721.5 6746377.9, 265718 6746376.4, 265718.8 6746371.9, 265717.5 6746366.9, 265718.9 6746362.4, 265722.9 6746361.4, 265724.4 6746364.9, 265726 6746372.4, 265730 6746371.3, 265731.5 6746367.8, 265730.4 6746364.8, 265729.8 6746357.8, 265733.4 6746355.8, 265738.3 6746352.8, 265728.2 6746340.9, 265727.7 6746337.4, 265731.2 6746337.8, 265749.2 6746338.7, 265768.2 6746337.2, 265780.2 6746338.4, 265809.6 6746334.7, 265816.7 6746339.7, 265823.1 6746337.1, 265827.1 6746335.1, 265833.1 6746333, 265852.6 6746331.4, 265854 6746325.9, 265854.5 6746322.4, 265833 6746325, 265825.1 6746328.1, 265821.1 6746326.1, 265818.1 6746327.4, 265813.1 6746326.2, 265806.1 6746328.2, 265800.1 6746326.8, 265784.1 6746329.7, 265780.1 6746328.5, 265774.1 6746330.5, 265770.1 6746329.2, 265766.1 6746330.6, 265762.1 6746329.3, 265753.1 6746330.7, 265745.1 6746329.7, 265740.1 6746328.8, 265730.2 6746330.9, 265723.1 6746328.9, 265719.2 6746330.9, 265715.2 6746329, 265712.7 6746330.5, 265710.2 6746329, 265707.7 6746330.5, 265682.2 6746327.3, 265675.8 6746328.6, 265676.7 6746332.8, 265671.7 6746332.8, 265670.7 6746329.8, 265666.2 6746327.9, 265660.2 6746328.9, 265654.2 6746323.5, 265652.709 6746320.319))`

**Comment by j3r3m1** [comment]
Perfect !

**Comment by j3r3m1** [comment]
good job. Even if I do not really understand why you have so many tests in one single test. =)

**Comment by gpetit** [comment]
> Even if I do not really understand why you have so many tests in one single test. =)

Yes ... at the beginning there was few.
Maybe in the future I'll divide them ...

**Pull request merged**
