### PR TITLE
BDTopo and OSM workflow now return the name of the computed tables.

### PR DESCRIPTION
**Pull request by ebocher**
The method getResults() on the OSM and BDTopo workflow returns the name of the computed tables and stored in the local database.
The input parameter has been improved. So the user can send a configuration file or a map to the workflow.

```java
 def osm_parmeters = [
                "description" :"Example of configuration file to run the grid indicators",
                "geoclimatedb" : [
                        "folder" : "/tmp/geoclimate",
                        "name" : "geoclimate_chain_db;AUTO_SERVER=TRUE",
                        "delete" :false
                ],
                "input" : [
                        "osm" : ["Paimpol"]],
                "output" :[
                        "folder" : ["path":  "/tmp/geoclimate",
                                    "tables": ["grid_indicators", "zones", "rsu_lcz"]]],
                "parameters":
                        ["distance" : 0,
                         "grid_indicators": [
                                 "x_size": 1000,
                                 "y_size": 1000,
                                 "indicators": ["LCZ_PRIMARY"]
                         ]
                        ]
        ]
IProcess process = OSM.WorkflowOSM.workflow()
process.execute(input: osm_parmeters)
process.getResults().output["Pont-de-Veyle"]
```
will return a map with a key = Pont-de-Veyle and value = name of tables

If the local H2GIS is not deleted after the workflow chain, the user can process the tables stored in the database.

### CODE REVIEW

**Comment by ebocher** [comment]
Since last H2 update with some errors 
```
Timeout trying to lock table "SURFACE_ACTIVITE"; SQL statement:
```

**Comment by ebocher** [comment]
Dear @katzyn 
Since the last update on H2 we have some lock issue.
I'm not able to find where it appears. 
The H2 database is build with this path "./target/${RsuIndicatorsTests.simpleName}_db;AUTO_SERVER=TRUE"

**Comment by katzyn** [comment]
Do you have a complete test case?

**Comment by ebocher** [comment]
Not yet a clear stack trace.
I'm on it

**Comment by katzyn** [comment]
H2 uses a very small lock timeout by default, usually it needs to be increased for applications with concurrent sessions and transactions.

But timeout may also indicate a some kind of deadlock.

**Comment by ebocher** [comment]
has the  lock timeout changed recently ?

**Comment by katzyn** [comment]
No.

**Comment by ebocher** [comment]
This code was working before 2.1.210 with 2.0.206.
I'm try to find a unit test but it's a huge sql chain ;((

**Comment by ebocher** [comment]
I modified the tests to create a new database each time because it was impossible to isolate a unit test

**Comment by ebocher** [comment]
@katzyn
The issue is fixed. It was a bad used of setAutocommit on H2GIS side.

**Comment by ebocher** [comment]
@katzyn
The issue is fixed. It was a bad used of setAutocommit on H2GIS side.

**Pull request merged**
